import { registerProtocol } from './registry';
import workoutProtocol from './body/workout/index';
import peptideProtocol from './body/peptides/index';
import nutritionProtocol from './body/nutrition/index';
import creditProtocol from './money/credit/index';
import incomeProtocol from './money/income/index';
import citizenshipProtocol from './travel/citizenship/index';
import skincareProtocol from './image/skincare/index';
import mindProtocol from './mind/index';
import purposeProtocol from './purpose/index';
import environmentProtocol from './environment/index';
import communityProtocol from './community/index';

registerProtocol(workoutProtocol);
registerProtocol(peptideProtocol);
registerProtocol(nutritionProtocol);
registerProtocol(creditProtocol);
registerProtocol(incomeProtocol);
registerProtocol(citizenshipProtocol);
registerProtocol(skincareProtocol);
registerProtocol(mindProtocol);
registerProtocol(purposeProtocol);
registerProtocol(environmentProtocol);
registerProtocol(communityProtocol);
