// lib/constants/countries.js
// ISO 3166-1 most likely shipping destinations for advnce labs wholesale.
// Covers the US + top 60 international markets. Anything else: buyer picks
// "Other" and free-texts the state/region field.

export const COUNTRIES = [
  'United States',
  'Canada',
  'Mexico',
  'United Kingdom',
  'Ireland',
  'Germany',
  'France',
  'Spain',
  'Portugal',
  'Italy',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Austria',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Iceland',
  'Poland',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Greece',
  'Cyprus',
  'Malta',
  'Bulgaria',
  'Croatia',
  'Slovenia',
  'Slovakia',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Turkey',
  'Israel',
  'United Arab Emirates',
  'Saudi Arabia',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'South Africa',
  'Egypt',
  'Morocco',
  'Nigeria',
  'Kenya',
  'India',
  'Pakistan',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Indonesia',
  'Philippines',
  'Vietnam',
  'Hong Kong',
  'Taiwan',
  'South Korea',
  'Japan',
  'Australia',
  'New Zealand',
  'Brazil',
  'Argentina',
  'Chile',
  'Colombia',
  'Peru',
  'Uruguay',
  'Costa Rica',
  'Panama',
  'Dominican Republic',
  'Other',
];
