-- Insert 65 injectable SKUs from Eve's oil.xls (received 2026-04-24).
-- Source sheet: docs/vendors/eve-oil-pricing.json
-- All active=false (hidden from storefront). DO NOT flip active without explicit legal clearance.
-- Contents: Schedule III AAS (testosterone esters, tren, deca/NPP, EQ, mast, primo, winstrol, blends),
-- oral-in-oil (Dbol/Anadrol/Superdrol), specialty (DHB/DHT/MENT/metribolone), HRT (Estradiol Cypionate),
-- Clenbuterol tabs, vitamin IMs (NAD+/D3/B12), lipotropic + wellness blends.
-- Duplicates skipped: LC120 (LIPO120 exists), LC216 (LIPO216 exists).
-- ON CONFLICT DO NOTHING for safe re-run.

BEGIN;

INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Clenbuterol', '40mcg x 100 tabs', 'Weight Loss', 'Eve', 130.0, 50, 0, 'EVE-C250', '🔴', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Testosterone Enanthate', '2500mg / 10ml (250mg/ml)', 'Anabolic', 'Eve', 130.0, 50, 0, 'EVE-E250', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Testosterone Enanthate', '3000mg / 10ml (300mg/ml)', 'Anabolic', 'Eve', 145.0, 60, 0, 'EVE-E300', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Testosterone Undecanoate', '3000mg / 10ml (300mg/ml)', 'Anabolic', 'Eve', 200.0, 80, 0, 'EVE-TY300', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Testosterone Propionate', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 120.0, 50, 0, 'EVE-P100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Testosterone Propionate', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 130.0, 50, 0, 'EVE-P200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Testosterone Suspension Blend', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 130.0, 50, 0, 'EVE-SP100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Test Base (TNE)', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 130.0, 50, 0, 'EVE-BA100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Sustanon 250', '2500mg / 10ml (250mg/ml)', 'Anabolic', 'Eve', 170.0, 70, 0, 'EVE-S250', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Sustanon 400', '4000mg / 10ml (400mg/ml)', 'Anabolic', 'Eve', 220.0, 90, 0, 'EVE-S400', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Supertest 450', '4500mg / 10ml (450mg/ml)', 'Anabolic', 'Eve', 230.0, 90, 0, 'EVE-S450', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Testo-600 Blend', '6000mg / 10ml (600mg/ml)', 'Anabolic', 'Eve', 200.0, 80, 0, 'EVE-T600', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Trenbolone Base', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 160.0, 65, 0, 'EVE-BR50', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Trenbolone Acetate', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 220.0, 90, 0, 'EVE-R100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Trenbolone Enanthate', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 220.0, 90, 0, 'EVE-RY100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Trenbolone Enanthate', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 330.0, 130, 0, 'EVE-R200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Trenbolone Hexahydrobenzyl Carbonate', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 400.0, 160, 0, 'EVE-H100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Tren Mix 200 (Ace + Enanthate)', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 330.0, 130, 0, 'EVE-RM200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Tri-Tren 225 (Ace + Ena + Hex)', '2250mg / 10ml (225mg/ml)', 'Anabolic', 'Eve', 480.0, 190, 0, 'EVE-3R225', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Blend 300 (Tren-A + Mast-P + Test-P)', '3000mg / 10ml (300mg/ml)', 'Anabolic', 'Eve', 400.0, 160, 0, 'EVE-B300', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Blend 375 (Tren-E + Mast-E + Test-E)', '3750mg / 10ml (375mg/ml)', 'Anabolic', 'Eve', 450.0, 180, 0, 'EVE-B375', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Blend 500 (Tren-E + Mast-E)', '5000mg / 10ml (500mg/ml)', 'Anabolic', 'Eve', 680.0, 270, 0, 'EVE-B500', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Ripex 225 (Tren-A + Mast-P + Test-P)', '2250mg / 10ml (225mg/ml)', 'Anabolic', 'Eve', 290.0, 120, 0, 'EVE-RX225', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Methenolone Enanthate (Primo)', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 480.0, 190, 0, 'EVE-M100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Methenolone Enanthate (Primo)', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 850.0, 340, 0, 'EVE-M200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Nandrolone Decanoate (Deca)', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 220.0, 90, 0, 'EVE-N200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Nandrolone Decanoate (Deca)', '3000mg / 10ml (300mg/ml)', 'Anabolic', 'Eve', 280.0, 110, 0, 'EVE-N300', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Nandromix 300 (NPP + Deca)', '3000mg / 10ml (300mg/ml)', 'Anabolic', 'Eve', 280.0, 110, 0, 'EVE-NM300', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('NPP (Nandrolone Phenylpropionate)', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 150.0, 60, 0, 'EVE-PN100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('NPP (Nandrolone Phenylpropionate)', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 220.0, 90, 0, 'EVE-PN200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Stanozolol Oil Base (Winstrol)', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 120.0, 50, 0, 'EVE-SO50', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Stanozolol Oil Base (Winstrol)', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 120.0, 50, 0, 'EVE-SO100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Stanozolol Suspension (Winstrol)', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 120.0, 50, 0, 'EVE-SW50', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Stanozolol Suspension (Winstrol)', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 120.0, 50, 0, 'EVE-SW100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Boldenone Undecylenate (EQ)', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 160.0, 65, 0, 'EVE-U200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Boldenone Undecylenate (EQ)', '3000mg / 10ml (300mg/ml)', 'Anabolic', 'Eve', 200.0, 80, 0, 'EVE-U300', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Boldenone Undecylenate (EQ)', '6000mg / 10ml (600mg/ml)', 'Anabolic', 'Eve', 330.0, 130, 0, 'EVE-U600', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Boldenone Cypionate', '2500mg / 10ml (250mg/ml)', 'Anabolic', 'Eve', 180.0, 70, 0, 'EVE-BS250', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Drostanolone Propionate (Mast)', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 250.0, 100, 0, 'EVE-D100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Drostanolone Enanthate (Mast)', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 450.0, 180, 0, 'EVE-D200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Mast Blend 200 (E + P)', '2000mg / 10ml (200mg/ml)', 'Anabolic', 'Eve', 450.0, 180, 0, 'EVE-DM200', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Dianabol Injectable (Methandrostenolone)', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 180.0, 70, 0, 'EVE-DO50', '🔴', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Anadrol Injectable (Oxymetholone)', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 160.0, 65, 0, 'EVE-OXO50', '🔴', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Superdrol Injectable (Methyldrostanolone)', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 160.0, 65, 0, 'EVE-SDO50', '🔴', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('DHB Injectable (1-Testosterone Cypionate)', '1000mg / 10ml (100mg/ml)', 'Anabolic', 'Eve', 250.0, 100, 0, 'EVE-1T100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('MENT (Trestolone Acetate)', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 570.0, 230, 0, 'EVE-MN50', '🔴', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Stanolone (DHT)', '500mg / 10ml (50mg/ml)', 'Anabolic', 'Eve', 150.0, 60, 0, 'EVE-HD50', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Metribolone (Methyltrienolone)', '50mg / 10ml (5mg/ml)', 'Anabolic', 'Eve', 150.0, 60, 0, 'EVE-BM5', '🔴', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Estradiol Cypionate', '100mg / 10ml (10mg/ml)', 'Hormonal', 'Eve', 130.0, 50, 0, 'EVE-EC100', '🟠', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('NAD+', '1000mg / 10ml (100mg/ml)', 'Longevity', 'Eve', 150.0, 75, 0, 'EVE-NJ100', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('GHK-Cu + Glutathione Blend', '4020mg / 10ml (GHK-Cu 2mg + GSH 200mg + His 100 + Gly 50 + NADH 50)', 'Skin', 'Eve', 130.0, 65, 0, 'EVE-GGH', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Vitamin D3', '200000 IU / 10ml (20k IU/ml)', 'Pharma', 'Eve', 80.0, 40, 0, 'EVE-D320', '🟢', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('B12 (Methylcobalamin)', '10mg / 10ml (1mg/ml)', 'Pharma', 'Eve', 40.0, 20, 0, 'EVE-B1201', '🟢', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('B12 (Methylcobalamin)', '100mg / 10ml (10mg/ml)', 'Pharma', 'Eve', 70.0, 35, 0, 'EVE-B1210', '🟢', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('L-Carnitine', '5000mg / 10ml (500mg/ml)', 'Weight Loss', 'Eve', 60.0, 30, 0, 'EVE-LC500', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Lipo-C FOCUS (ATP + Eria Jarensis + Carnitine)', '4250mg / 10ml', 'Weight Loss', 'Eve', 120.0, 60, 0, 'EVE-LC425', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Lipo-C FAT BLASTER (Carnitine + MIC + B-complex)', '5260mg / 10ml', 'Weight Loss', 'Eve', 130.0, 65, 0, 'EVE-LC526', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Super Shred (Carnitine + MIC + Albuterol + B12)', '5530mg / 10ml', 'Weight Loss', 'Eve', 130.0, 65, 0, 'EVE-LC553', '🔴', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Shred (Carnitine + MIC + B-complex)', '3503mg / 10ml', 'Weight Loss', 'Eve', 120.0, 60, 0, 'EVE-SHR', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Lipo Mino Mix (MIC + Carnitine + B-complex)', '2444mg / 10ml', 'Weight Loss', 'Eve', 100.0, 50, 0, 'EVE-LMX', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Relaxation PM (GABA + Melatonin + Arg + Glu)', '2260mg / 10ml', 'Sleep', 'Eve', 130.0, 65, 0, 'EVE-RP226', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Sleep Blend (GABA + His + Theanine + Taurine + Melatonin)', '3520mg / 10ml', 'Sleep', 'Eve', 120.0, 60, 0, 'EVE-SZ352', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Super Human Blend (9-Amino Mix)', '8650mg / 10ml', 'Recovery', 'Eve', 130.0, 65, 0, 'EVE-SHB', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Hair Skin Nails Blend (B-complex + Biotin)', '1503mg / 10ml', 'Skin', 'Eve', 130.0, 65, 0, 'EVE-HHB', '🟡', false) ON CONFLICT (sku) DO NOTHING;
INSERT INTO products (name, size, cat, vendor, cost, retail, stock, sku, risk, active) VALUES ('Immune Blend (Glutathione + Vit C + Zinc)', '4025mg / 10ml', 'Immune', 'Eve', 150.0, 75, 0, 'EVE-GAZ', '🟡', false) ON CONFLICT (sku) DO NOTHING;

COMMIT;
